name: CI Pipeline

on:
  push:
    branches:
      - main
      - rahul-feature

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check project files
        run: |
          echo "Checking project..."
          ls -la

      - name: Check index.html
        run: |
          test -f index.html
          echo "index.html exists"
